jobs:
  build-debug:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.8.2
    - continue-on-error: true
      name: build app apk
      run: ./gradlew :app:assembleChargeDebug;
    - continue-on-error: true
      name: build imitate apk
      run: ./gradlew :imitate:assembleDebug;
  build-release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: build app apk
      run: ./gradlew :app:assembleChargeRelease;
    - continue-on-error: true
      name: build imitate apk
      run: ./gradlew :imitate:assembleRelease;
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
